import os

class ReportGenerator:
    """
    Generates a human-readable forensic report from analysis results.
    """

    def generate(self, analysis_result, output_path="forensic_report.md"):
        print("[*] Generating forensic report...")

        summary = analysis_result.get("summary", "")
        findings = analysis_result.get("findings", [])
        anomalies = analysis_result.get("anomalies", [])
        timeline = analysis_result.get("timeline", {}).get("events", [])

        lines = []

        # ---------------------------------------
        # Header
        # ---------------------------------------
        lines.append("# Forensic Analysis Report\n")
        lines.append("Generated by Forensic AI Agent\n")
        lines.append("---\n")

        # ---------------------------------------
        # Summary
        # ---------------------------------------
        lines.append("## Executive Summary\n")
        lines.append(summary + "\n")

        # ---------------------------------------
        # Findings
        # ---------------------------------------
        lines.append("## Findings\n")
        if findings:
            for f in findings:
                lines.append(f"- **{f['type']}**: {f['reason']}")
        else:
            lines.append("No findings detected.")
        lines.append("")

        # ---------------------------------------
        # Anomalies
        # ---------------------------------------
        lines.append("## Anomalies\n")
        if anomalies:
            for a in anomalies:
                lines.append(f"- **{a['type']}**: {a['reason']}")
        else:
            lines.append("No anomalies detected.")
        lines.append("")

        # ---------------------------------------
        # Timeline
        # ---------------------------------------
        lines.append("## Unified Timeline\n")
        for event in timeline:
            ts = event["timestamp"]
            src = event["source"]
            details = event["details"]
            lines.append(f"- `{ts}` — **{src}** — {details}")
        lines.append("")

        # ---------------------------------------
        # Write file
        # ---------------------------------------
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_path
