import os

class ReportGenerator:
    """
    Generates a human-readable forensic report from analysis results.
    """
    SEVERITY_LABELS = {
        4: "Critical",
        3: "High",
        2: "Medium",
        1: "Low"
    }

    def generate(self, analysis_result, output_path="forensic_report.md"):
        print("[*] Generating forensic report...")

        summary = analysis_result.get("summary", "")
        findings = analysis_result.get("findings", [])
        anomalies = analysis_result.get("anomalies", [])
        timeline = analysis_result.get("timeline", {}).get("events", [])

        lines = []

        # ---------------------------------------
        # Header
        # ---------------------------------------
        lines.append("# Forensic Analysis Report\n")
        lines.append("Generated by Forensic AI Agent\n")
        lines.append("---\n")

        # ---------------------------------------
        # Summary
        # ---------------------------------------
        lines.append("## Executive Summary\n")
        if isinstance(summary, dict):
            lines.append(f"Findings: {summary.get('finding_count', 0)}\n")
            lines.append(f"Anomalies: {summary.get('anomaly_count', 0)}\n")
        else:
            lines.append(str(summary) + "\n")

        # ---------------------------------------
        # Findings (Grouped by Severity)
        # ---------------------------------------
        lines.append("## Findings by Severity\n")

        groups = self.group_findings_by_severity(findings)

        for sev in [4, 3, 2, 1]:
            label = self.SEVERITY_LABELS.get(sev, f"Severity {sev}")
            lines.append(f"### {label} Severity\n")

            if not groups.get(sev):
                lines.append("_No findings in this category._\n")
                continue

            # Sort by timestamp
            sorted_group = sorted(groups[sev], key=lambda f: f.get("timestamp", 0))

            for f in sorted_group:
                reason = f.get("reason") or f.get("path") or "(no details)"
                lines.append(f"- **{f['type']}** — {reason}")

            lines.append("")

        # ---------------------------------------
        # Findings (Grouped by Severity)
        # ---------------------------------------
        lines.append("## Findings by Severity\n")

        groups = self.group_findings_by_severity(findings)

        for sev in [4, 3, 2, 1]:
            label = self.SEVERITY_LABELS.get(sev, f"Severity {sev}")
            lines.append(f"### {label} Severity\n")

            if not groups.get(sev):
                lines.append("_No findings in this category._\n")
                continue

            # Sort by timestamp
            sorted_group = sorted(groups[sev], key=lambda f: f.get("timestamp", 0))

            for f in sorted_group:
                reason = f.get("reason") or f.get("path") or "(no details)"
                lines.append(f"- **{f['type']}** — {reason}")

            lines.append("")

        # ---------------------------------------
        # Timeline
        # ---------------------------------------
        lines.append("## Unified Timeline\n")
        for event in timeline:
            ts = event.get("timestamp")
            src = event.get("source")
            details = event
            lines.append(f"- `{ts}` — **{src}** — {details}")
        lines.append("")

        # ---------------------------------------
        # Write file
        # ---------------------------------------
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_path

    def group_findings_by_severity(self, findings):
        groups = {4: [], 3: [], 2: [], 1: []}
        for f in findings:
            sev = f.get("severity", 1)
            groups.setdefault(sev, []).append(f)
        return groups
