import os

class ReportGenerator:
    """
    Generates a human-readable forensic report from analysis results.
    """

    def generate(self, analysis_result, output_path="forensic_report.md"):
        print("[*] Generating forensic report...")

        summary = analysis_result.get("summary", "")
        findings = analysis_result.get("findings", [])
        anomalies = analysis_result.get("anomalies", [])
        timeline = analysis_result.get("timeline", {}).get("events", [])

        lines = []

        # ---------------------------------------
        # Header
        # ---------------------------------------
        lines.append("# Forensic Analysis Report\n")
        lines.append("Generated by Forensic AI Agent\n")
        lines.append("---\n")

        # ---------------------------------------
        # Summary
        # ---------------------------------------
        lines.append("## Executive Summary\n")
        if isinstance(summary, dict):
            lines.append(f"Findings: {summary.get('finding_count', 0)}\n")
            lines.append(f"Anomalies: {summary.get('anomaly_count', 0)}\n")
        else:
            lines.append(str(summary) + "\n")

        # ---------------------------------------
        # Findings
        # ---------------------------------------
        lines.append("## Findings\n")
        if findings:
            for f in findings:
                reason = f.get("reason", f.get("path", ""))
                lines.append(f"- **{f['type']}**: {reason}")
        else:
            lines.append("No findings detected.")
        lines.append("")

        # ---------------------------------------
        # Anomalies
        # ---------------------------------------
        lines.append("## Anomalies\n")
        if anomalies:
            for a in anomalies:
                reason = a.get("reason", a.get("path", ""))
                lines.append(f"- **{a['type']}**: {reason}")
        else:
            lines.append("No anomalies detected.")
        lines.append("")

        # ---------------------------------------
        # Timeline
        # ---------------------------------------
        lines.append("## Unified Timeline\n")
        for event in timeline:
            ts = event.get("timestamp")
            src = event.get("source")
            details = event
            lines.append(f"- `{ts}` — **{src}** — {details}")
        lines.append("")

        # ---------------------------------------
        # Write file
        # ---------------------------------------
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return output_path
